version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    restart: unless-stopped
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped
