name: CI/CD to AWS

on:
  push:
    branches: [main]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps and run healthcheck
        working-directory: nasa-project/backend
        run: |
          pip install -r requirements.txt
          python app.py &
          PID=$!
          sleep 3
          curl -fsS --retry 5 --retry-delay 2 http://localhost:5000/api/health
          kill $PID || true

  deploy:
    needs: test-backend
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_SSH_KEY }}
          script_stop: true
          script: |
            set -euo pipefail
            cd /home/ubuntu/devops-pet/nasa-project

            git fetch origin
            git reset --hard origin/main

            docker compose down

            docker compose build --no-cache backend frontend

            docker compose up -d --force-recreate
