name: CI/CD to AWS

on:
  push:
    branches: [main]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Клонировать репозиторий
        uses: actions/checkout@v3

      - name: Установить Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Установить зависимости backend
        run: |
          cd nasa-project/backend
          pip install -r requirements.txt

      - name: Запустить backend и проверить healthcheck
        run: |
          python nasa-project/backend/app.py &
          sleep 3
          curl -f http://localhost:5000/api/health

  deploy:
    needs: test-backend
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            cd /home/ubuntu/devops-pet/nasa-project
            git pull
            docker composr down
            docker compose up --build -d
